// swift-tools-version:5.9
// The swift-tools-version declares the minimum version of Swift required to build this package.
//
// Auto-generated by swift-openapi-bootstrapper
// Generated at: 2026-02-19T21:02:19.801178

import PackageDescription

let package = Package(
    name: "MistralAPI",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
        .tvOS(.v16),
        .watchOS(.v9),
    ],
    products: [
        .library(
            name: "MistralAPITypes",
            targets: ["MistralAPITypes"]
        ),
        .library(
            name: "MistralAPI",
            targets: ["MistralAPI"]
        ),
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-openapi-generator.git", from: "1.10.4"),
        .package(url: "https://github.com/apple/swift-openapi-runtime.git", from: "1.9.0"),
        .package(url: "https://github.com/swift-server/swift-openapi-async-http-client", from: "1.3.0"),
        .package(url: "https://github.com/atacan/UsefulThings", branch: "main"),
    ],
    targets: [
        // Types target: Contains generated types from OpenAPI spec
        .target(
            name: "MistralAPITypes",
            dependencies: [
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime")
            ]
        ),
        // Client target: Contains generated client and custom code
        .target(
            name: "MistralAPI",
            dependencies: [
                .product(name: "OpenAPIRuntime", package: "swift-openapi-runtime"),
                .product(name: "OpenAPIAsyncHTTPClient", package: "swift-openapi-async-http-client"),
                .target(name: "MistralAPITypes"),
            ]
        ),
        // Tests
        .testTarget(
            name: "MistralAPITests",
            dependencies: [
                .target(name: "MistralAPI"),
                .product(name: "UsefulThings", package: "UsefulThings"),
            ],
            resources: [.process("Resources")]
        ),
    ]
)
